### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by kabirvirji** [kabirvirji/colortherapy#1]
## Step 0: Landing Page
This page is responsible for communicated to the user what the app is for, and provide a gif showing the various app actions. 
- Login with Spotify button
- This step deals with the Spotify auth process: https://developer.spotify.com/documentation/general/guides/authorization-guide/
- After the user is authorized they are re-directed to the next step
![MacBook Pro - 3](https://user-images.githubusercontent.com/11722981/78503695-1b0fd200-771d-11ea-8030-0f8a3b967e2c.png)

## Step 1: Color Calibration 
The user is asked to use a slider to indicate how energetic they are feeling. They are also asked their opinions on 6 different colors. These values will be our `energy` and `valence` respectively 
![Component 8](https://user-images.githubusercontent.com/11722981/78503781-970a1a00-771d-11ea-9cd5-214fa7cc2ea4.png)

> possible colors

![Component 4](https://user-images.githubusercontent.com/11722981/78503790-a5f0cc80-771d-11ea-94ab-1a02f28e10aa.png)

## Step 2: Choosing Colors
Now that we know how the user associates colors, we can let them choose colors. 

- when a color is clicked, the "my colors" bubble pops up indicating the chosen color
- the clicked color is visibly clicked (communicated with a border, or shadow)
- the bubble is **dynamic** which means it moves to a different part of screen if you try to hover
- to delete a color from "my colors" the user can unclick the color from the main page
- once the minimum number of colors are picked, a "generate playlist" button appears (and stays) at the bottom of the page
- once the "generate playlist" button is clicked we display a loading, and success message

![Component 9](https://user-images.githubusercontent.com/11722981/78503950-cd946480-771e-11ea-9bc8-9238ebb95414.png)

## how picking colors and valence works

The user is asked to identify how they feel about 6 different colors. These serve as our base valence, for example:

```
{
  "red": 0.2, // the user rated red 2/10
  "green": 0.1,
  "blue": 0.5,
  "yellow": 0.7,
  "white": 0.3,
  "black": 0.1
}
```

Then, the user is asked to choose colors from the main page (minimum 5). We can then compute the "visual difference" (`deltaE`) of these colors, and find their **closest** base color. 

Once we know the closest colors, we can compute their average valence using our valence values from the object above. 

> an example

![Component99](https://user-images.githubusercontent.com/11722981/78504240-a179e300-7720-11ea-9b6d-68507a2adcaa.png)

The valence value is calculated in a script I wrote here: https://gist.github.com/kabirvirji/20dc9f2e85010891591592f855ed207f

## Searching Spotify 
This is the endpoint we will be using: https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/

Seed artists and tracks are how we personalize the query, and we can get a users top artists or tracks using the following endpoint: https://developer.spotify.com/documentation/web-api/reference/personalization/get-users-top-artists-and-tracks/

The `get-recommendations` endpoint only supports a **combination of 5** artist or track seeds. We get more variance if just provide the user's top five artists (rather than tracks)

We will be using the following query parameters:
`seed_artists`, `min_energy`, `max_energy`, `target_energy`, `min_valence`, `max_valence`, `target_valence`

min and max energy will be calculated using the floor and ceil of the chosen *energy* value, and min and max valence will be calculated using the minimum base color valence, and maximum base color valence. 

From the API response we can make a playlist of 10 tracks based on the colors the user chose

**Comment by paulxuca** [comment]
Nice
